// Layer 3: AI legitimacy evaluation for PUBLIC self-serve trial signups.
//
// Judges whether a signup looks like a real automobile dealership from the
// signup's OWN submitted fields. This is the layer that actually catches the
// 2026-09-03 pattern ("bob" / "alice victim", dealership == contact name,
// throwaway domain, a Puerto Rico zip on a business with no other PR signal) —
// the deterministic gates in lib/signup-guard.ts can't, because those domains
// publish MX and passed Turnstile like any real browser.
//
// PRIVACY: the prompt contains ONLY the fields this signup submitted. No other
// customer's data, no fleet statistics, no database contents are ever sent.
//
// FAIL-SAFE: any timeout, API error, refusal, or unparseable response returns
// verdict "error", and the caller routes "error" to human review. We never
// auto-provision because the model was unavailable.

import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";

// Sonnet: this is a short classification on a latency-sensitive path, and it
// matches the model tier already used for the platform's other content calls.
export const LEGITIMACY_MODEL = "claude-sonnet-5";
// Hard ceiling so a slow model call can never hang a signup. The route treats
// a timeout as "error" → review queue.
const TIMEOUT_MS = 8_000;

// Validated with zod, but the SCHEMA sent to the API is hand-written JSON
// Schema rather than generated by the SDK's zodOutputFormat helper: that helper
// expects zod v4's internals (`_zod.def`) and this project is on zod ^3.25, so
// it throws "Cannot read properties of undefined (reading 'def')". Writing the
// schema out avoids a zod major bump on a security-path change.
const VerdictSchema = z.object({
  verdict: z.enum(["legit", "suspicious", "fake"]),
  confidence: z.number().min(0).max(1),
  reasons: z.array(z.string()).min(1).max(6),
});

// Structured-output schemas accept types, enums, required and
// additionalProperties — but NOT numeric/array bound keywords: sending
// `minimum`/`maximum` on a number returns
// `400 output_config.format.schema: For 'number' type, properties maximum,
// minimum are not supported`. The bounds live in VerdictSchema instead, which
// validates the response on our side, so an out-of-range confidence still
// routes to human review rather than being trusted.
const VERDICT_JSON_SCHEMA = {
  type: "object" as const,
  properties: {
    verdict: { type: "string", enum: ["legit", "suspicious", "fake"] },
    confidence: { type: "number", description: "0 to 1" },
    reasons: { type: "array", items: { type: "string" }, description: "1 to 6 short reasons" },
  },
  required: ["verdict", "confidence", "reasons"],
  additionalProperties: false,
};

export type LegitimacyVerdict = {
  verdict: "legit" | "suspicious" | "fake" | "error" | "skipped";
  confidence: number;
  reasons: string[];
  model: string;
  ms: number;
};

/**
 * Auto-provision only on a confident "legit". Everything else → review.
 *
 * Calibrated against real traffic (2026-09-03): the three known fakes scored
 * verdict=fake at 0.97-0.99, while real dealerships scored verdict=legit at
 * 0.68-0.97 — the low end being an independent lot on a gmail address
 * ("Grubbs Auto Revival"), exactly the shape that must NOT be held up. The
 * verdict itself is the primary signal and the gap between the two clusters is
 * wide, so this floor only needs to catch low-conviction "legit" calls. At 0.7
 * it wrongly held that indie lot; 0.6 clears it while leaving a ~0.37 margin
 * to the nearest fake. Raise it only with data, and watch
 * /admin/trial-signups for held rows that should have gone through.
 */
export const AUTO_APPROVE_MIN_CONFIDENCE = 0.6;

export function shouldAutoProvision(v: LegitimacyVerdict): boolean {
  return v.verdict === "legit" && v.confidence >= AUTO_APPROVE_MIN_CONFIDENCE;
}

const SYSTEM = `You screen free-trial signups for DealerAddendums, a SaaS product used by franchised and independent US automobile dealerships to print window addendum stickers.

Decide whether a signup looks like a REAL automobile dealership, or a fake/test/bot submission.

Signals that a signup is REAL:
- A dealership name that reads like an actual dealer: a family or place name plus a franchise or "Auto Group"/"Motors"/"Automotive" ("Gettel Hyundai of Sarasota", "Tuttle-Click Ford", "Sharp Automotive").
- A work email on the dealership's own domain, a dealer-group domain, or a plausible personal address for a small independent lot.
- A contact name that reads like a real person's name and is DIFFERENT from the dealership name.
- A US ZIP that is plausible for a car dealership.

Signals that a signup is FAKE or a test:
- Placeholder, joke, or cryptography-textbook names: "test", "asdf", "bob", "alice", "foo", "demo", "x", or anything containing "victim"/"attacker"/"hacker".
- The dealership name is identical to (or a trivial variant of) the contact name — real dealerships are not named after the person filling in the form.
- A dealership name that is not a business name at all (a single first name, a single letter, random characters).
- An email local-part that looks generated ("bob11", "alice0105", long random strings) on a domain with no automotive or business identity.
- A ZIP that is implausible for the claimed business, or obvious filler.

Be decisive but fair. Independent used-car lots often have plain names and free email addresses — that alone is NOT fake; weigh it with the other signals. When the dealership name is a credible business name, prefer "legit" even if the email is a free provider.

Return your verdict, a confidence between 0 and 1, and 1-6 short reasons citing the specific fields that drove it.`;

export async function evaluateSignupLegitimacy(input: {
  email: string;
  name: string;
  dealership: string;
  zip?: string | null;
  phone?: string | null;
  accountKind?: "single" | "group";
  groupName?: string | null;
}): Promise<LegitimacyVerdict> {
  const started = Date.now();
  const base: Omit<LegitimacyVerdict, "verdict" | "confidence" | "reasons"> = {
    model: LEGITIMACY_MODEL, ms: 0,
  };

  if (!process.env.ANTHROPIC_API_KEY) {
    // Unconfigured is not "safe to allow" — send it to a human.
    return { verdict: "error", confidence: 0, reasons: ["ANTHROPIC_API_KEY not configured"], ...base, ms: 0 };
  }

  // ONLY this signup's own fields. Nothing else.
  const facts = [
    `Dealership name: ${input.dealership}`,
    `Contact name: ${input.name}`,
    `Email: ${input.email}`,
    `Email domain: ${input.email.split("@")[1] ?? "(none)"}`,
    `ZIP: ${input.zip?.trim() || "(not provided)"}`,
    `Phone: ${input.phone?.trim() || "(not provided)"}`,
    `Account type requested: ${input.accountKind ?? "single"}`,
    ...(input.groupName ? [`Group name: ${input.groupName}`] : []),
  ].join("\n");

  try {
    const client = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
      maxRetries: 1, // one retry; the timeout below is the real ceiling
    });
    const res = await client.messages.create({
      model: LEGITIMACY_MODEL,
      max_tokens: 1024,
      system: SYSTEM,
      // Low effort: this is a short judgement, not a research task.
      output_config: {
        effort: "low",
        format: { type: "json_schema", schema: VERDICT_JSON_SCHEMA },
      },
      messages: [{ role: "user", content: `Screen this trial signup:\n\n${facts}` }],
    }, { timeout: TIMEOUT_MS });

    const ms = Date.now() - started;

    // A safety refusal is not a legitimacy signal — send it to a human.
    if (res.stop_reason === "refusal") {
      return { verdict: "error", confidence: 0, reasons: ["model declined to answer"], ...base, ms };
    }
    // Structured outputs guarantee the shape, but validate anyway — a malformed
    // verdict must route to human review, never be coerced into an approval.
    const text = res.content.filter((b) => b.type === "text").map((b) => b.text).join("");
    let parsed: z.infer<typeof VerdictSchema>;
    try {
      parsed = VerdictSchema.parse(JSON.parse(text));
    } catch {
      return { verdict: "error", confidence: 0, reasons: [`model returned no parseable verdict: ${text.slice(0, 120)}`], ...base, ms };
    }
    return { verdict: parsed.verdict, confidence: parsed.confidence, reasons: parsed.reasons, ...base, ms };
  } catch (err) {
    const ms = Date.now() - started;
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[signup-legitimacy] evaluation failed:", msg);
    return { verdict: "error", confidence: 0, reasons: [`evaluation failed: ${msg.slice(0, 160)}`], ...base, ms };
  }
}
